# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get python-pyaudio python3-pyaudio

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Hazboun6
  password:
    secure: FizzyFrog66?
  on:
    tags: true
    repo: nanograv/tabletop_pta
    python: 3.6
